version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - mysqldb
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
      MYSQL_URL: jdbc:mysql://mysqldb:3307/test

  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test