server:
  port: 8000

spring:
  datasource:
    url: jdbc:h2:mem:CompanyManagementTest
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console.enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
    show-sql: true
    open-in-view: true

