spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_management
    username: root
    password: 12345678
    driverClassName: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always

  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    open-in-view: true