#spring:
#  datasource:
#    url: jdbc:mysql://${PROD_DB_HOST}:${PROD_DB_PORT}:/${PROD_DB_NAME}
#    username: ${PROD_DB_USERNAME}
#    password: ${PROD_DB_PASSWORD}
#    name: company-crud

sql:
  init:
    mode: always


server:
  port: 8081
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

jpa:
  hibernate.ddl-auto: update
  show-sql: true
  open-in-view: true






