server:
  port: 8000

#  datasource:
#    url: jdbc:mysql://mysqldb:3307/test?allowPublicKeyRetrieval=true&useSSL=false
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver

spring:
  devtools:
    livereload:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3307/CompanyManagement?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    open-in-view: true
